omnique/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # home page

    path('', views.about, name='about'),
    path('price-list/', views.price_list, name='price_list'),
    path('contact-us/', views.contact, name='contact'),
    path('browse-items/', views.browse_items, name='browse_items'),
    path('prodcuts/<int:id>/', views.product_details, name='product_details')
    ##path('member-<int:member_id>/', views.member_page, name='member'),
]

sites/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('omnique.urls')),
    path('omnique-content-editor/', admin.site.urls),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

omnique/models.py
from django.db import models

# product model
class Product(models.Model):
    name = models.CharField(max_length=64)
    description = models.TextField(max_length=512)
    registered_designs = models.ManyToManyField('Design')
    registered_tags = models.ManyToManyField('Tag')
    price = models.DecimalField(max_digits=999,decimal_places=2)
    has_price_range = models.BooleanField(default=False)
    category_options = {('AD','Adults\' Clothing'),('CH','Childrens\' Clothing'),('BB','Baby Clothes'),('OT','Other Products')}
    category = models.CharField(max_length=2,choices=category_options,default="OT")
    img = models.FileField(upload_to='images/products/')


    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'
        ordering = ['name']

    def __str__(self):
        return self.name

# design model
class Design(models.Model):
    name = models.CharField(max_length=64)
    img = models.FileField(upload_to='images/designs/')

    class Meta:
        verbose_name = 'Design'
        verbose_name_plural = 'Designs'
        ordering = ['name']

    def __str__(self):
        return self.name

# tag model
class Tag(models.Model):
    name = models.CharField(max_length=64, blank=True)

    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'
        ordering = ['name']

    def __str__(self):
        return self.name

omnique/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(max_length=50,
                           widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    confirm_email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))

omnique/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound
from django.urls import reverse
from .forms import *
from django.core.mail import EmailMessage
import csv
import os
from .models import Product

def about(request):
    return render(request, "omnique/about.html")

def price_list(request):
    #temp views while e-commerce being implemented
    working_path = os.path.dirname(os.path.abspath(__file__))
    file_path = os.path.join(working_path, 'static/omnique/files/priceList.csv')
    with open(file_path, 'r') as file:
        reader = csv.reader(file)
        price_list = list(reader)

    return render(request, "omnique/shop.html", {'price_list': price_list})

def contact(request):
    resp = False
    if request.method == 'POST':
        # create a form instance and populate it with data from the request
        form = ContactForm(request.POST)
        # check whether it's valid
        if form.is_valid():
            # get post data
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            re_email = form.cleaned_data['confirm_email']
            message = form.cleaned_data['message']

            if re_email != email:
                vmail = True
                return render(request, "omnique/contact.html", {'form' : form, 'vmail' : vmail})

            message_to_email = "From: %s at %s \nMessage:\n%s" % (name, email, message)

            subject_to_email = "%s\'s Enquiry" % (name)

            try:
                email = EmailMessage(subject_to_email, message_to_email, to=['example@email.com'])
                email.send(fail_silently=False)
                # send to new url
                return HttpResponseRedirect(reverse('contact'))
            except:
                resp=True
                form = ContactForm()

    # if a GET (or any other method) we'll create a blank form
    else:
        form = ContactForm()
    return render(request, "omnique/contact.html", {'form' : form, 'resp' : resp})

def browse_items(request):
    categories = Product.category_options
    if request.method == 'POST':
        checked_boxes = request.POST.getlist('checks')
        if(len(checked_boxes)==0):
            products = Product.objects.all()
        else:
            products = Product.objects.filter(category__in=checked_boxes)
    else:
        products = Product.objects.all()
    return render(request, "omnique/browseItems.html", {'products':products, 'categories':categories})

def product_details(request, id):
    try:
        product = Product.objects.get(pk=id)
    except:
        return HttpResponseNotFound("No such product!")
    return render(request, "omnique/productDetails.html", {'product': product})

omnique/templates/omnique/about.html
{% extends 'omnique/base.html' %}

{% load static %}

{% block content %}

<script>
$(document).ready(function() {
  document.title = "About Us";
  $("p.title").text("About Us");
  $("#about").addClass("active");
});
</script>


  <div class="jumbotron">
    <div class="jumbotron-child">
      <h1 class="heading">We are Omnique!</h1>
      <hr>
      <p>We strive to give everyone unique designs and personalised items at an affordable price. From clothing to glassware to keepsakes. You can have it all!</p>
    </div>
  </div>

  <div class="container">
    <div id="carousel" class="carousel slide" data-ride="carousel">

      <!-- Indicators -->
      <ul class="carousel-indicators">
        <li data-target="#carousel" data-slide-to="0" class="active"></li>
        <li data-target="#carousel" data-slide-to="1"></li>
        <li data-target="#carousel" data-slide-to="2"></li>
        <li data-target="#carousel" data-slide-to="3"></li>
        <li data-target="#carousel" data-slide-to="4"></li>
        <li data-target="#carousel" data-slide-to="5"></li>
      </ul>

      <!-- The slideshow -->
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="{% static 'omnique/img/carousel/omniqueMerch.jpg' %}" alt="Omnique Merch">
          <div class="carousel-caption">
            <h3>Omnique Merchandise</h3>
          </div>
        </div>
        <div class="carousel-item">
          <img src="{% static 'omnique/img/carousel/mugTable.jpg' %}" alt="Mug on table">
          <div class="carousel-caption">
            <h3>Personalised Designs</h3>
          </div>
        </div>
        <div class="carousel-item">
          <img src="{% static 'omnique/img/carousel/clothing.jpg' %}" alt="Omnique t-shirts">
          <div class="carousel-caption">
            <h3>Clothing</h3>
          </div>
        </div>
        <div class="carousel-item">
          <img src="{% static 'omnique/img/carousel/glass.jpg' %}" alt="Glass">
          <div class="carousel-caption">
            <h3>Glassware</h3>
          </div>
        </div>
        <div class="carousel-item">
          <img src="{% static 'omnique/img/carousel/koozie.jpg' %}" alt="Can koozie">
          <div class="carousel-caption">
            <h3>Gifts</h3>
          </div>
        </div>
        <div class="carousel-item">
          <img src="{% static 'omnique/img/carousel/stoolToys.jpg' %}" alt="Stool with toys">
          <div class="carousel-caption">
            <h3>Keepsakes</h3>
          </div>
        </div>
      </div>

      <!-- Left and right controls -->
      <a class="carousel-control-prev" href="#carousel" data-slide="prev">
        <span class="carousel-control-prev-icon"></span>
      </a>
      <a class="carousel-control-next" href="#carousel" data-slide="next">
        <span class="carousel-control-next-icon"></span>
      </a>

    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="card">
          <div class="card-header">
            <h5 class="card-title">Omnique</h5>
          </div>
          <div class="card-body">
            <img class="sectionImage" src="{% static 'omnique/img/icons/logoBlue.png' %}" alt="">
            <p class="card-text">
              The name <i>Omnique</i> comes from the Latin 'omni' meaining <i>all</i> and the Greek-French '-ique' meaning
              <i>having the form of</i>. We are a family run company and felt this name reflected on our core values perfectly;
              everyone is a part of the Omnique family, it is equally fair and accessable to all as well as considerate and reflective of
              everybodies wishes. If you have an idea about what you would like, we at Omnique want to try make it real. "Omnique" means
              having the form of everybody. In other words, Omnique is me, Omnique is you, Omnique is all of us.
            </p>
          </div>
        </div>
        <!-- <div class="highlight-box">
          <h4>Omnique</h4>
          <img class="sectionImage" src="{% static 'omnique/img/icons/logoBlue.png' %}" alt=""><br>
          <p class="sectionP">
            The name <i>Omnique</i> comes from the Latin 'omni' meaining <i>all</i> and the Greek-French '-ique' meaning
            <i>having the form of</i>. We are a family run company and felt this name reflected on our core values perfectly;
            everyone is a part of the Omnique family, it is equally fair and accessable to all as well as considerate and reflective of
            everybodies wishes. If you have an idea about what you would like, we at Omnique want to try make it real. "Omnique" means
            having the form of everybody. In other words, Omnique is me, Omnique is you, Omnique is all of us.
          </p>
        </div> -->
        <br>
      </div>
      <div class="col-md-4">
        <div class="card">
          <div class="card-header">
            <h5 class="card-title">Homemade</h5>
          </div>
          <div class="card-body">
            <i style="display:inline-block;width:100%;text-align:center;" class="fas fa-home fa-7x py-3"></i>
            <p class="card-text">
              Omnique isn't a large company. In fact, there are only two of us! We make everything from home, and we're proud of
              that fact. Each item is hand crafted with care - everything is checked more than once so we give you the most perfect products.
              The greatest thing about our products being homemade is that you're truely getting a personalised experience because no
              two items are ever identical.
            </p>
          </div>
        </div>
          <!-- <img class="sectionImage" src="{% static 'omnique/img/icons/shirt.png' %}" alt=""><br> -->
          <br>
      </div>
      <div class="col-md-4">
        <div class="card">
          <div class="card-header">
            <h5 class="card-title">Care</h5>
          </div>

          <div class="card-body">
            <div></div>
            <i style="display:inline-block;width:100%;text-align:center;" class="far fa-heart fa-7x py-3"></i>
            <p class="card-text">
              Most importantly omnique stands for community. We are not here to capatalise by taking advantage of good people. We want
              to work with you so you get the best possible deal. Thats why we encourage you to contact us. We give you the opportunity to
              talk to a real person and as a result we can personally research your requested items to bring you the greatest price. Also,
              by messaging us directly, we can get a better idea of what you want so that we can make your ideas a reality.
            </p>
          </div>
        </div>
          <!-- <img class="sectionImage" src="{% static 'omnique/img/icons/heart.png' %}" alt=""><br> -->
      </div>
    </div>
  </div>

  <!-- our products 1 page content -->
  <div id="adult" class="container">
    <br><br>
    <div class="row align-items-center">
      <div class="col-md-6">
        <h1 class="heading">Adults</h1>
        <p class="productDesc">
          Omnique sells many adult clothing, ranging from t-shirts (our main seller) to different kinds of hoodies and
          jumpers. Each can be pressed with an wonderfully made design of your choice, or even make a request if nothing
          suits your particular taste.
        </p>
      </div>
      <div class="col-md-6">
        <img class="img-fluid" src="{% static 'omnique/img/apparel/omniqueShirt.jpg' %}" alt="">
      </div>
    </div>
  </div>

  <div id="kids" class="container">
    <br><br>
    <div class="row align-items-center">
      <div class="col-md-6">
        <img class="img-fluid" src="{% static 'omnique/img/apparel/childPinkClothes.jpg' %}" alt="">
      </div>
      <div style="text-align:right;" class="col-md-6">
        <h1 class="heading">Kids</h1>
        <p class="productDesc">
          Perfect for gifts at seasonal times and birthdays. Children can show off their cool design tailored to them.
          From dinosaurs to trains, from animals to unique monster creations - pick out a design the child will love. We do many types of clothing such as: T-shirts, hoodies and joggers.
          Check out our price list today or contact us for more information.
        </p>
      </div>
    </div>
  </div>

  <div id="babies" class="container">
    <br><br>
    <div class="row align-items-center">
      <div class="col-md-6">
        <h1 class="heading">Babies</h1>
        <p class="productDesc">
          We sell things like baby grows, scratch mitts and bibs. All can be personalised. Suggestion: why not
          put the date of birth on an item of clothing? Perhaps a 12 month series of baby grows for their first year? Drop us an email, a message on
          social media, or use our <a href="{% url 'contact' %}">contact us</a> page today!
        </p>
      </div>
      <div class="col-md-6">
        <img class="img-fluid" src="{% static 'omnique/img/apparel/kidsClothes.jpg' %}" alt="">
      </div>
    </div>
  </div>

  <!-- our products 2 page content -->
  <div id="ranges" class="container">
    <br><br>
    <div class="row align-items-center">
      <div class="col-md-6">
        <img class="img-fluid" src="{% static 'omnique/img/apparel/pillow.jpg' %}" alt="">
      </div>
      <div style="text-align:right;" class="col-md-6">
        <h1 class="heading">Ranges</h1>
        <p class="productDesc">
          Seasonal items, celebrations and big events lead us to release different ranges. Ever wanted a Mr & Mrs mug set? Looking for a bespoke item for
          Valentine's day? Going to a baby shower and want something just a little more special? Give us a shout!
        </p>
      </div>
    </div>
  </div>

  <div id="glassware" class="container">
    <br><br>
    <div class="row align-items-center">
      <div class="col-md-6">
        <h1 class="heading">Glassware</h1>
        <p class="productDesc">
          We do a variety of glassware at Omnique, including Tumblers, Wine Glasses, Prosecco Flutes,
          Pint Glasses, Tankards and even Vases.
        </p>
      </div>
      <div class="col-md-6">
        <img class="img-fluid" src="{% static 'omnique/img/apparel/twoGlasses.jpg' %}" alt="">
      </div>
    </div>
  </div>

  <div id="keepsakes" class="container">
    <br><br>
    <div class="row align-items-center">
      <div class="col-md-6">
        <img class="img-fluid" src="{% static 'omnique/img/apparel/book.jpg' %}" alt="">
      </div>
      <div style="text-align:right;" class="col-md-6">
        <h1 class="heading">Keepsakes</h1>
        <p class="productDesc">
          Sometimes personalised gifts are the ones people remember the most. It means a lot to a person who is close to you, and impacts on those
          who aren't. Omnique offers a range of personalisation on lots of different items.
        </p>
      </div>
    </div>
  </div>

  <div id="custom" class="container">
    <br><br>
    <div class="row align-items-center">
      <div class="col-md-6">
        <h1 class="heading">Large Orders</h1>
        <p class="productDesc">
          Are you planning a big event?
          Maybe you want wedding favours personalised or fancy getting yourself and others some T-shirts for the big stag/hen night?
          Want to offer merchandise for your business/society/club? Then come to us! We offer a bulk-buy service and guarantee, if a supplier
          gives us a better deal for buying in bulk, the price <i>you</i> pay will reflect this. We are here to give you top quality items at a top
          quality price, not to capitalise on the fact you're in need of our service. Our service to you goes beyond providing products - we're also
          here to give you great value so you feel valued in return.
        </p>
      </div>
      <div class="col-md-6">
        <img class="img-fluid" src="{% static 'omnique/img/apparel/otley.jpg' %}" alt="">
      </div>
    </div>
  </div>

{% endblock %}

omnique/templates/omnique/base.html
<html>

<head>
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, inital-scale=1">
<!-- Custom style sheet -->
<link rel="stylesheet" type="text/css" href="{% static 'omnique/style.css' %}">
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
<script type="text/javascript" src="{% static 'omnique/scripts.js' %}"></script>
<script src="https://kit.fontawesome.com/ec7b5b425d.js"></script>
<title></title>
</head>

<body data-spy="scroll" data-target=".navbar" data-offset="50">

  <div class="thumbnail text-center">
      <img src="{% static 'omnique/img/placeholder.jpg' %}" alt="" class="img-responsive">
      <div class="post-content">
          <p class="title"></p>
      </div>
  </div>
  <nav class="navbar navbar-expand-md bg-company-gold navbar-light" data-toggle="sticky-onscroll">
    <!-- Brand -->
    <a class="navbar-brand" href="{% url 'about' %}">
      <img height="50px" src="{% static 'omnique/img/icons/logoBlack.png' %}" alt="logo">
    </a>

    <!-- Toggler/collapsibe Button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Navbar links -->
    <div class="collapse navbar-collapse justify-content-end" id="navbar">
      <ul class="navbar-nav">
        <li id="about" class="nav-item"><a class="nav-link" href="{% url 'about' %}">About Us</a></li>
        <li id="store" class"nav-item"><a class="nav-link" href="{% url 'price_list' %}">Price List</a></li>
        <li id="browse" class"nav-item"><a class="nav-link" href="{% url 'browse_items' %}">Browse Items</a></li>
        <li id="contact" class="nav-item"><a class="nav-link" href="{% url 'contact' %}">Contact Us</a></li>
      </ul>
    </div>
  </nav>

  {% block content %}
  {% endblock %}

  <div class="container">
    <hr>
    <footer>
      <p>&copy; All rights reserved - Omnique Designs</p>
    </footer>
  </div>

</body>

</html>

omnique/templates/omnique/browseItems.html
{% extends 'omnique/base.html' %}

{% load static %}

{% block content %}

<script>

$(document).ready(function() {
  document.title = "Browse Items";
  $("p.title").text("Browse Items");
  $("#browse").addClass("active");
});
</script>

<div class="container-fluid">
  <h1 class="heading">
    Browse
  </h1>
  <hr>

  <!-- filter control -->
  <div class="row p-4">
    <form action="{% url 'browse_items' %}" method="post" style="width:100%">
      {% csrf_token %}
      {% for category in categories %}
      <div class="filter-check">
        <input id="{{category.0}}" type="checkbox" name="checks" value="{{category.0}}">
        <label for="{{category.0}}">{{category.1}}</label>
      </div>
      {% endfor %}
      <button id="submit" type="submit" class="btn btn-secondary">Submit</button>
    </form>
  </div>
  <hr>

  <!-- products -->
  <div class="row">
    {% for product in products %}
      <div class="col-12 col-md-2 {{product.category}}">
        <a class="card-link" data-toggle="modal" data-target="#product_modal" href="#" data-href="{% url 'product_details' id=product.id %}">
          <div class="card">
            <img class="card-img-top" src="{{product.img.url}}" alt="{{product.name}}">
            <div class="card-body">
              <h5 class="card-title">{{product.name}}<i class="float-right">{% if product.has_price_range %}from {% endif %}&pound;{{product.price}}</i></h5>
              <i>{{product.get_category_display}}</i>
            </div>
          </div>
        </a>
        <br>
      </div>
    {% endfor %}
  </div>

</div>

<div class="modal fade" id="product_modal" tabindex="-1" role="dialog" aria-labelledby="#modal_label" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title float-left" id="modal_label">Product Details</h4>
        <button type="button" class="close float-right" data-dismiss="modal" aria-hidden="true">&times;</button>
      </div>
      <div class="modal-body">
          <iframe id="product_frame" src="" width="100%" height="80%" frameborder="0" allowtransparency="true"></iframe>
      </div>
    </div>
  </div>
</div>

<script>
  $("a.card-link").click( function(e) {
    e.preventDefault();
    var src = $(this).attr("data-href");
    $(".modal").find("iframe").attr("src", src);
  });
</script>
{% endblock %}

omnique/templates/omnique/contact.html
{% extends 'omnique/base.html' %}

{% load static %}

{% block content %}

<script>
$(document).ready(function() {
  document.title = "Contact Us";
  $("p.title").text("Contact Us");
  $("#contact").addClass("active");
});
</script>

  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2 style="text-align:center;">Leave us a message!</h2><br>
      </div>
    </div>
    <div class="row align-items-center">
      <div class="col-md-6">
        <form action="{% url 'contact' %}" method="post">
          {% if vmail %}
          <p style="color:red;">Emails do not match.</p>
          {% endif %}
          {% csrf_token %}
          {% if form.subject.errors %}
                <ol role="alertdialog">
                    {% for error in form.subject.errors %}
                    <li role="alert"><strong>{{ error|escape }}</strong></li>
                    {% endfor %}
                </ol>
                {% endif %}

                {% for field in form %}
                <div class="fieldWrapper form-group" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                    {{ field.label_tag }}{% if field.field.required %}<span class="required">*</span>{% endif %}
                    {{ field }}
                    {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
                {% endfor %}
            <input  class="btn btn-primary" type="submit" value="Submit">
        </form>
        {% if resp %}
        <p style="color:red;background:white;">Message Failed To Send!<p>
        {% endif %}
        <br>
      </div>
      <div class="col-md-6" style="font-size:16pt;">
        <p id="contactInfo">
          <div style="display:inline-block;width:100%;text-align:center;">
            <i class="fab fa-facebook-square fa-2x align-middle"></i>
            <a href="https://www.facebook.com/omnique.designs" target="_blank">@omnique.designs</a>
          </div><br><br><br>
          <div style="display:inline-block;width:100%;text-align:center;">
            <i class="fab fa-instagram fa-2x align-middle"></i>
            <a href="https://www.instagram.com/omnique.designs" target="_blank">@omnique.designs</a>
          </div><br><br><br>
          <div style="display:inline-block;width:100%;text-align:center;">
            <i class="far fa-envelope fa-2x align-middle"></i> omnique.designs@gmail.com
          </div>
        </p>
      </div>
    </div>
  </div>

{% endblock %}

omnique/templates/omnique/productDetails.html
{% load static %}
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, inital-scale=1">
<!-- Custom style sheet -->
<link rel="stylesheet" type="text/css" href="{% static 'omnique/style.css' %}">

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<!-- jQuery library -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<!-- Latest compiled JavaScript -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<script src="https://kit.fontawesome.com/ec7b5b425d.js"></script>
<title>{{product.name}}</title>
</head>

<body>
<div class="p-2 pl-3">
  <h1 class="heading">{{product.name}}<i class="float-right">{% if product.has_price_range %}from {% endif %}&pound;{{product.price}}</i></h1>
  <div class="row" style="height:70%;">
    <div class="col-9">
      <img class="img-fluid rounded" style="height:100%;" src="{{product.img.url}}"></img>
    </div>
    <div class="col-3 overflow-auto">
      {% for design in product.registered_designs.all %}
        <div class="col-12">
          <img class="img-fluid rounded" src="{{design.img.url}}">
        </div>
      {% endfor %}
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <hr>
      <p class="m-2">{{product.description}}</p>
    </div>
  </div>
</div>
<!-- {{product.description}} -->
<!-- <strong>Tags</strong><br> -->
<!-- {% for tag in product.registered_tags.all %} -->
<!-- {{tag.name}}, -->
<!-- {% endfor %} -->
<!-- <br> -->
<!-- <strong>Designs</strong><br> -->
<!-- {% for design in product.registered_designs.all %} -->
<!-- {{design.name}} - {{design.img.url}}<br> -->
<!-- {% endfor %} -->

</body>

</html>

omnique/templates/omnique/shop.html
{% extends 'omnique/base.html' %}

{% load static %}

{% block content %}

<script>
$(document).ready(function() {
  document.title = "Price List";
  $("p.title").text("Price List");
  $("#store").addClass("active");
});
</script>

  <div class="container">
    <p>
      <b>All prices</b> are based on <b>designs</b> created by <b>Omnique designs</b>. Use of <b>other designs may increase the cost</b> of items due to having to source new vinyl
      or other materials. <b>Discounts</b> will also apply on an <b>individual order basis</b> due to <b>supplier discount</b> for <b>bulk orders</b> of the same product.
    </p>
  </div>

  <div class="container">
    <h1 class="heading">Price List</h1>
    <div class="table-responsive">
    <table class="table">
      {% for row in price_list %}
        {% if row.0 == 'h'%}
        <thead>
          <tr>
            <th colspan="4">{{ row.1 }}</th>
          </tr>
        <thead>
        {% elif row.0 == 'n'%}
        <tr>
          <td colspan="4">*{{ row.1 }}</td>
        </tr>
        {% else %}
        <tr>
          <td>{{row.0}}</td>
          <td>{{row.1}}</td>
          <td>&#163;{{row.2}}</td>
          <td>
            {% if row.3 != "" %}
            &#163;{{row.3}}
            {% endif %}
          </td>
        </tr>
        {% endif %}
      {% endfor %}
    </table>
    </div>
  </div>

{% endblock %}